### ISSUE TITLE
import suggestion

### ISSUE THREAD

**Issue by grafst** [ManufacturaInd/python-zenlog#9]
Great Package, love the simplicity!
I alway import it as follows:
```
try: from zenlog import log as logging 
except: import logging
logging.info("info")
```
That way if zenlog is not installed the logs still work.
Is that smart, or am I missing something?
If not, maybe others could profit of it, if you would put it in the readme. I could also make a pullrequest, but I'm not so used to github-etiquette ;)

best stephan

**Comment by rlafuente** [comment]
This made my day! Cheers!

Happy to merge your pull request if you can take care of that -- thank you!

**Comment by grafst** [comment]
see: #10

**Comment by rlafuente** [comment]
awesome, thanks :-)
